name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: List files
        run: ls -la backend  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t harith47/alliswell:latest backend
          docker push harith47/alliswell:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull harith47/alliswell:latest

      - name: Stop & Remove Old Container
        run: docker rm -f nodejs-app-container || true  

      - name: Run Backend Container
        run: |
          docker run -d --name nodejs-app-container \
            -p 5000:5000 \
            -v /home/ubuntu/app-images:/app/public/images \
            harith47/alliswell:latest

      - name: Restart Nginx
        run: docker restart nginx-proxy || docker run -d --name nginx-proxy \
          -p 80:80 -p 443:443 \
          -v $HOME/nginx-config/nginx.conf:/etc/nginx/nginx.conf \
          nginx

      - name: Clean Up Dangling Images
        run: docker image prune -f  
